title: IsThereAnyCode
description: Hello :) I'm Jayden
theme: just-the-docs
baseurl: ""
url: https://IsThereAnyCode.github.io/IsThereAnyCode

aux_links:
  Template Repository: https://IsThereAnyCode.github.io/IsThereAnyCode

color_scheme: dark

remote_theme : mmistakes/minimal-mistakes

permalink: pretty

