title: IsThereAnyCode
description: Hello :) I'm Jayden
theme: just-the-docs

url: https://IsThereAnyCode.github.io/IsThereAnyCode

aux_links:
  Template Repository: https://IsThereAnyCode.github.io/IsThereAnyCode

